### ISSUE TITLE
Unknown dimensions after loadImage fulfilled

### ISSUE THREAD

**Issue by pepa-linha** [nittro/dropzone#1]
Hi,

maybe I would expect `fulfilled` will be called on `image` load event because otherwise image information is not available.

https://github.com/nittro/dropzone/blob/db0e2a46c0fd25c4f1faa4f766e07976a42cbeeb/src/DropZone.js#L398

```js
zone.loadImage(file).then(function (image) {
    image.width; // returns 0 in Firefox
});
```

**Comment by jahudka** [comment]
good point, thanks, fixed! try updating to dropzone 2.0.8 / extras 2.0.33 :-)
